### ISSUE TITLE
Reveal.js 2.6.1 being used in master branch

### ISSUE THREAD

**Issue by kfuglsang** [fsprojects/FsReveal#40] opened 2015-02-28 18:07 UTC
When cloning the master branch and running build.cmd the build process downloads Reveal.js 2.6.1 (commit id 9da952fea30906090446d038430186b11dba7f13).

The develop branch grabs a much newer commit (id 20d858deb888fe0ec0ba92a919c8a0526ac52a2e).

**Comment by forki** [comment] 2015-03-01 08:59
fixed in 0.3.3

**Comment by forki** [comment] 2015-03-03 07:57
Reopened because of twitter discussion.

**Comment by forki** [comment] 2015-03-03 07:59
Actually I can't reproduce with FsReveal 0.5:

![image](https://cloud.githubusercontent.com/assets/57396/6458413/646d0594-c183-11e4-80e3-230a12073dcc.png)

![image](https://cloud.githubusercontent.com/assets/57396/6458423/7da097a6-c183-11e4-91c1-685d632be434.png)

what are the steps you do to reproduce?

**Comment by kfuglsang** [comment] 2015-03-03 08:05
git clone git@github.com:fsprojects/FsReveal.git
cd FsReveal
./build.cmd

This gives 2.6.1.

If I then change the FsReveal version in paket.lock to 0.5.0 then ./build.cmd fails.
Could not generate slides for: C:\Users\kfc\Desktop\FsReveal\slides\index.md
Could not load file or assembly 'FSharp.Literate, Version=2.7.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
Could not generate slides for: C:\Users\kfc\Desktop\FsReveal\slides\sample.fsx
Could not load file or assembly 'FSharp.Literate, Version=2.7.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by forki** [comment] 2015-03-03 08:08
please retry

**Comment by kfuglsang** [comment] 2015-03-03 08:11
![Awesome](http://media.giphy.com/media/iVr5SN6w5irMQ/giphy.gif)

**Comment by forki** [comment] 2015-03-03 08:13
![facepalm](https://cloud.githubusercontent.com/assets/57396/6458595/971a22b8-c185-11e4-9849-8a1fb146e09c.gif)

I forgot to `git push`....

**Closed by forki** 2015-03-03 08:13 UTC
